### ISSUE TITLE
Adding other site buttons

### ISSUE THREAD

**Issue by iam-Shashank** [marioortizmanero/reddit-search-on-google#2]
Great work! Suggestion: would be great to have options for some other sites like stackoverflow, github, producthunt. Reason being that many a times, when I am searching for a project, code i search on all 3: reddit,stackexchange,github. Right now, I just duplicate tab(assigned a mouse button to do:Ctrl+l+c+t+v+enter) and append the website names.

Or, maybe custom config to trigger X tabs with different "site:website.com".  1 click solution.
Also, I am not familiar with the inner workings of TamperMonkey etc. My query is that would there be any technical roadblocks if this script was made into a separate chrome extension?

**Comment by marioortizmanero** [comment]
I thought of this a while ago but had a couple issues:

 * How would the user add more sites? I tried to create some kind of GUI using the Google pop-up for when you click on `Tools` but it was a bit complicated. I could try again though.

* Related to the last question, where does the user get the icons from? Can he just upload them? Or use fontawesome?

Creating an extension wouldn't be a bad idea. It was initially a tampermonkey userscript because the way it works may be a bit unreliable. But it would fix the "GUI" issue, since it could be done from the extension settings. I've never done a Chrome/Firefox extension though, so I'd have to investigate a bit. And I'm also not that good at javascript haha. I kinda got lost at the promises part. 

Thanks for the idea, I'll start working on it once I have more time :)

**Comment by iam-Shashank** [comment]
Good questions. So, just FYI I am not a web-dev (more ML/Data Science), I am mainly talking wrt to features, and I might not be aware of technical pain points. 
So, I was thinking about hardcoding some specific sites(say 4-5 popular ones), and their icons. Either within the script (but that would crowd the user's toolbar against their wish) or a checkbox UI, where you just click which sites you want.
A more advanced version would be having checkboxes for combination of n websites, wherein clicking 1 button would open 3(n) diff tabs with those "site:website.com". 

Busy whole December(exams), but will try to hack together or point you towards potential similar open source chrome extension implementation. (Here's one: https://greasyfork.org/en/scripts/7543-google-search-extra-buttons). Bad UI. but it was trying something similar. Look at screenshots at the bottom of the webpage.

This is in my personal interest too, since, I spend a lot of time googling and duplicating tabs and appending  reddit,github, stackexchange.  Literally doing it for the past 1 week vigorously😂. Will try my best to help in adding these features.
Me. Right Now(all those tabs): 
![image](https://user-images.githubusercontent.com/34963991/69476283-480eb880-0dfe-11ea-8c04-6d06879e7c11.png)

**Comment by marioortizmanero** [comment]
Yeah I'm not a web dev either but the extension is so helpful I could definitely work on it more. 

About the hard-coded sites: I think I have a better idea. The extension would let you import and export saves of your config, which would contain the sites you added and such. This would be necessary for me because I have multiple computers and it would be nice to sync them easily. The thing is that there could be a default one with all these sites already customized. They'd appear disabled and could be removed so no problem there.

I'll take a look at that extension, thanks for the link. I have exams on January myself so I can do some work before I start. 

Should I make a new repo for this? I won't remove the original script because it's still nice if you only want it for reddit.

Also, nice screenshot you got there hahaha

**Comment by iam-Shashank** [comment]
Yup, I agree. Import/export configs makes sense. Also, I thought this extension would be mainly used by power users, and very useful for developers, journalists, researchers for narrowing down their search, so, giving them the option to add any website would make sense. As for the icon, taking an icon of just the first letter of the URL would make sense(a lot of website follow this methodology while making user profile icons from username initials).
It's totally upto you if you want to make a new repo. I think it would make sense to fork this and make a new repo. Agreed, this script is useful on its own, and for those who use/want to  ViolentMonkey/Tampermonkey etc. 

Also, just realized that the Advanced version I was suggesting wasn't well thought of. I have a different kinda UI (much better) in mind, though, not totally refined. Will explain it later.

**Comment by marioortizmanero** [comment]
Oh good idea! An icon with the initial letter would be easy to implement.

Also, what should the new repo's name be? Something along the lines of Google Site Search? Not sure what's best.

**Comment by iam-Shashank** [comment]
Repo's name can be changed later too. I'll update here, when I have a good name in mind. For now, just make it google-plus.🤣

**Comment by marioortizmanero** [comment]
Closing this as out of scope, as I don't have time to implement it in the foreseeable future. If anyone wants to take on it, I suggest they fork & upload their own version. Thanks!
