### ISSUE TITLE
Is it possible to add this to other search engines like Startpage?

### ISSUE THREAD

**Issue by e-t-l** [marioortizmanero/reddit-search-on-google#8]
Startpage serves anonymized and de-personalized google search results. In theory, it shouldn't be difficult to add this to any other search engine like DuckDuckGo. I think all it would take is figuring out which elements need to be added/changed for each site's layouts, which is unfortunately beyond my coding ability.

**Comment by marioortizmanero** [comment]
That could definitely work, yes. You are right that you just need to figure out what HTML IDs should be changed, and maybe add some extra functionality to handle all these search engines in a single script, instead of multiple ones.

I'm afraid I don't use that search engine myself, so I won't be able to maintain this feature. If you're interested, you can give it a try yourself. I would say it's very beginner-friendly, and it will help you learn programming, if that interests you :)
